# conda env create -f environment.yml
name: transcript-assembly-hisat2-stringtie
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - fastqc=0.11.8
  - trimmomatic=0.39
  - hisat2=2.1.0
  - samtools=1.9
  - stringtie=2.0
  - multiqc=1.7

