# conda env create -f environment.yml
name: functional-annotation-preparation
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - blast=2.9.0
  - openjdk>=11.0.1
  - elfutils=0.176
  - agat=1.0.0
